<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="<?= $base_uri[0]; ?>/public/assets/front/css/style.css">
</head 
<body>
    
<header id="header" class="">
    <div class="contHeader">
        <nav>
            <div id="menu">
                <ul>
                <li><a href="/pull/public/home">Accueil</a></li>
                <li><a href="/pull/public/products">Products</a></li>
                <li><a href="/pull/public/contact">Contact</a></li>
                <li><a href="/pull/public/profile">profile</a></li>

                </ul>
            </div>
            <div id="nav-icon3">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </div>
            <a href="#" class="logo">PullArty</a>
            
            <div class="navBtns">
                
            <div class="navLink">
                <div class=""><a href="/pull/public/home">Accueil</a></div>
                <div><a href="/pull/public/products">Products</a></div>
                <div><a href="/pull/public/contact">Contact</a></div>
                <div><a href="/pull/public/login">login</a></div>
                <div class=""><a href="/pull/public/profile">profile</a></div>
            </div>
            <div class="navBtn">
            <div></div>
            <div class="panier">
                <a class="svg" href="#"><svg viewBox="0 0 24 24" width="30px" height="30px" class="d Vb UmNoP"><path fill-rule="evenodd" clip-rule="evenodd" d="M4.5 4.75H2v-1.5h2.5c.779 0 1.354.398 1.71.844.339.423.54.959.54 1.406v.25h14.71l-1.874 7.5H6.75v1.25c0 .29.164.76.475 1.175.327.436.632.575.775.575h9a2.75 2.75 0 11-2.45 1.5h-3.1a2.75 2.75 0 11-4.645-.407c-.314-.219-.578-.499-.78-.768-.439-.585-.775-1.365-.775-2.075v-9a.95.95 0 00-.21-.469c-.144-.179-.319-.281-.54-.281zm4.5 13a1.25 1.25 0 100 2.5 1.25 1.25 0 000-2.5zm8 0a1.25 1.25 0 100 2.5 1.25 1.25 0 000-2.5zm-10.25-6h11.664l1.125-4.5H6.75v4.5z"></path></svg></a>
                <div class="numberPanier"><div>0</div></div>
            </div>
            </div>
            </div>
        </nav>
    </div>
</header>
