<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="/public/assets/front/css/style.css">
</head>
<body>
<nav>
    <a href="#" class="logo"></a>
    <div class="navBtn">
        <div></div>
        <div></div>
        <div>
            <li class="nav-item"><a href="?page=home">Accueil</a></li>
            <li class="nav-item"><a href="?page=products">Products</a></li>
            <li class="nav-item"><a href="?page=reservation">Réservation</a></li>
        </div>
    </div>
</nav>
  