<main>
    <div class="errorContainer">
    </div>
    <div class="register">
        <div class="container">
            <div class="card p-4 ">
                <div class="loginTitle">
                    <h4>Update Post</h4>
                </div>
                    
                    <div class="formBody">
                    <form class="addCard" method="post" enctype="multipart/form-data">
    
                        <div class="form-group">
                            <label class="labelInput">title</label>
                            <div class="inputGroup">
                                <div class="inputGroupPrepend">
                                    <span class="inputGroupText"><svg height="1em" fill="#44476a" viewBox="0 0 448 512"><path d="M224 256A128 128 0 1 0 224 0a128 128 0 1 0 0 256zm-45.7 48C79.8 304 0 383.8 0 482.3C0 498.7 13.3 512 29.7 512H418.3c16.4 0 29.7-13.3 29.7-29.7C448 383.8 368.2 304 269.7 304H178.3z"/></svg></span>
                                </div>
                                <input class="form-control"  type="text" name="title" placeholder="title"/>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label class="labelInput">subtitle</label>
                            <div class="inputGroup">
                                <div class="inputGroupPrepend">
                                    <span class="inputGroupText"><svg height="1em" fill="#44476a" viewBox="0 0 512 512"><path d="M48 64C21.5 64 0 85.5 0 112c0 15.1 7.1 29.3 19.2 38.4L236.8 313.6c11.4 8.5 27 8.5 38.4 0L492.8 150.4c12.1-9.1 19.2-23.3 19.2-38.4c0-26.5-21.5-48-48-48H48zM0 176V384c0 35.3 28.7 64 64 64H448c35.3 0 64-28.7 64-64V176L294.4 339.2c-22.8 17.1-54 17.1-76.8 0L0 176z"/></svg></span>
                                </div>
                                <input class="form-control"  type="text" name="subtitle" placeholder="subtitle"/>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label class="labelInput">content</label>
                            <div class="inputGroup">
                                <div class="inputGroupPrepend">
                                    <span class="inputGroupText"><svg  height="1em" fill="#44476a" viewBox="0 0 448 512"><path d="M224 64c-44.2 0-80 35.8-80 80v48H384c35.3 0 64 28.7 64 64V448c0 35.3-28.7 64-64 64H64c-35.3 0-64-28.7-64-64V256c0-35.3 28.7-64 64-64H80V144C80 64.5 144.5 0 224 0c57.5 0 107 33.7 130.1 82.3c7.6 16 .8 35.1-15.2 42.6s-35.1 .8-42.6-15.2C283.4 82.6 255.9 64 224 64zm32 320c17.7 0 32-14.3 32-32s-14.3-32-32-32H192c-17.7 0-32 14.3-32 32s14.3 32 32 32h64z"/></svg></span>
                                </div>
                                <input class="form-control"  type="text" name="content" placeholder="content"/>
                            </div>
                        </div>
                        
                        <label class="labelInput" for="img">Sélectionnez une image à télécharger :</label>
                        <br>
                        <input type="file" id="file" name="img">
                            
                        <div class="inputSubmitLogin">
                            <input type="submit" name="addPostForm" value="post"/>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
