<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="<?= $base_uri[0]; ?>/public/assets/admin/css/style.css">

</head>
<body>
    
<header id="header" class="">
    <div class="contHeader">
        <nav>
            <div id="menu">
                <ul>
                <li><a href="<?= $base_uri[0]; ?>/public/admin">admin</a></li>
                <li><a href="<?= $base_uri[0]; ?>/public/logout">deco</a></li>
                </ul>
            </div>
            <div id="nav-icon3">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </div>
            <a href="#" class="logo">PullArty</a>

            <div class="navBtns">
                
            <div class="navLink">
                <div><a href="<?= $base_uri[0]; ?>/public/admin">admin</a></div>
                <div><a href="<?= $base_uri[0]; ?>/public/logout">deco</a></div>
            </div>
            </div>
        </nav>
    </div>
</header>
