
<main>
    <?php 
    if(isset($_SESSION['user_name'])){
        echo $_SESSION['user_name'];
    }
    
    ?>
    <?php foreach($this->data as $post): ?>
    
    <article class="card cardArticle">
        <img src="<?= $base_uri[0]; ?>/public/assets/front/uploads/<?= $post->getImg(); ?>" alt="img article pull">
        <div class="date"><?= $post->getDate(); ?></div>
        <h2 class="mrg1"><?= $post->getTitle(); ?></h2>
        <p><?= $post->getSubtitle(); ?></p>
        <a class="btnHover" href="post/<?= $post->getId(); ?>">see more</a>
    </article>
    <?php endforeach; ?> 
</main>
