<div class="navSex">
    <div class="sex">
        Man
    </div>
    <div class="sex">
        Woman
    </div>
</div>

<main>
    <ul class="productsContainer">
        <?php foreach($this->data as $products): ?>
        <a href="product/<?= $products->getId(); ?>">
            <li  class="cardProduct">
                <div>
                <article>
                    <a href="product/<?= $products->getId(); ?>">
                        <img src="./../public/assets/front/img/moutonPrairi.jpg" alt="img article pull">
                    </a>
                    <h2 class="mrg1">
                        <p><?= $products->getName(); ?></p>
                    </h2>
                    <p><?= $products->getPrice(); ?>€</p>
                </article>
                </div>
            </li>
            </a>
        <?php endforeach; ?> 
    </ul>
</main>