
<main>
    <ul class="productsContainer">
        <?php foreach($this->data as $products): ?>
        <a href="product/<?= $products->getId(); ?>">
            <li  class="cardProduct">
                <div>
                <article>
                    <a href="product/<?= $products->getId(); ?>">
                        <img src="<?= $base_uri[0]; ?>/public/assets/front/uploads/<?= $products->getImg(); ?>" alt="img article pull">
                    </a>
                    <h2 class="mrg1">
                        <p><?= $products->getName(); ?></p>
                    </h2>
                    <div class="bottomProducts">
                        <p><?= $products->getPrice(); ?>€</p>
                        <a class="addPannier" href="/pull/public/addPanier/<?= $products->getId(); ?>">panier</a>
                    </div>
                </article>
                </div>
            </li>
            </a>
        <?php endforeach; ?> 
    </ul>
</main>