<main>
    <div class="ppUserChange">
        <img src="ppUser.jpg"></img>
    </div>
    <div><a href="/pull/public/login">login</a></div>
    <div><a href="/pull/public/register">register</a></div>
    <div><a href="/pull/public/logout">deco</a></div>
    <div class="panier">
        
        <button>Valis commands</button>
    </div>
    <div class="historyCommands">
        
    </div>
</main>

